classdef robot_SetMotionSupervisionRequest < robotics.ros.Message
    %robot_SetMotionSupervisionRequest MATLAB implementation of robot_comm/robot_SetMotionSupervisionRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'robot_comm/robot_SetMotionSupervisionRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '6aa33038f20fd360687b6932c639f0c9' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Supervision
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Supervision'} % List of non-constant message properties
        ROSPropertyList = {'supervision'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = robot_SetMotionSupervisionRequest(msg)
            %robot_SetMotionSupervisionRequest Construct the message object robot_SetMotionSupervisionRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function supervision = get.Supervision(obj)
            %get.Supervision Get the value for property Supervision
            supervision = double(obj.JavaMessage.getSupervision);
        end
        
        function set.Supervision(obj, supervision)
            %set.Supervision Set the value for property Supervision
            validateattributes(supervision, {'numeric'}, {'nonempty', 'scalar'}, 'robot_SetMotionSupervisionRequest', 'Supervision');
            
            obj.JavaMessage.setSupervision(supervision);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Supervision = obj.Supervision;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Supervision = strObj.Supervision;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Supervision = obj.Supervision;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.robot_comm.robot_SetMotionSupervisionRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.robot_comm.robot_SetMotionSupervisionRequest;
            obj.reload(strObj);
        end
    end
end
