classdef robot_SetSpeedRequest < robotics.ros.Message
    %robot_SetSpeedRequest MATLAB implementation of robot_comm/robot_SetSpeedRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'robot_comm/robot_SetSpeedRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '9f0ff1193cfb3499a7608d4091f40f93' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Tcp
        Ori
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Ori', 'Tcp'} % List of non-constant message properties
        ROSPropertyList = {'ori', 'tcp'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = robot_SetSpeedRequest(msg)
            %robot_SetSpeedRequest Construct the message object robot_SetSpeedRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function tcp = get.Tcp(obj)
            %get.Tcp Get the value for property Tcp
            tcp = double(obj.JavaMessage.getTcp);
        end
        
        function set.Tcp(obj, tcp)
            %set.Tcp Set the value for property Tcp
            validateattributes(tcp, {'numeric'}, {'nonempty', 'scalar'}, 'robot_SetSpeedRequest', 'Tcp');
            
            obj.JavaMessage.setTcp(tcp);
        end
        
        function ori = get.Ori(obj)
            %get.Ori Get the value for property Ori
            ori = double(obj.JavaMessage.getOri);
        end
        
        function set.Ori(obj, ori)
            %set.Ori Set the value for property Ori
            validateattributes(ori, {'numeric'}, {'nonempty', 'scalar'}, 'robot_SetSpeedRequest', 'Ori');
            
            obj.JavaMessage.setOri(ori);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Tcp = obj.Tcp;
            cpObj.Ori = obj.Ori;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Tcp = strObj.Tcp;
            obj.Ori = strObj.Ori;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Tcp = obj.Tcp;
            strObj.Ori = obj.Ori;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.robot_comm.robot_SetSpeedRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.robot_comm.robot_SetSpeedRequest;
            obj.reload(strObj);
        end
    end
end
