classdef robot_DeactivateCSSRequest < robotics.ros.Message
    %robot_DeactivateCSSRequest MATLAB implementation of robot_comm/robot_DeactivateCSSRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'robot_comm/robot_DeactivateCSSRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '0c45e35cd3184913d29b208e6e34ea32' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoseClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Pose') % Dispatch to MATLAB class for message type geometry_msgs/Pose
    end
    
    properties (Dependent)
        ToPose
    end
    
    properties (Access = protected)
        Cache = struct('ToPose', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ToPose'} % List of non-constant message properties
        ROSPropertyList = {'ToPose'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = robot_DeactivateCSSRequest(msg)
            %robot_DeactivateCSSRequest Construct the message object robot_DeactivateCSSRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function topose = get.ToPose(obj)
            %get.ToPose Get the value for property ToPose
            if isempty(obj.Cache.ToPose)
                obj.Cache.ToPose = feval(obj.GeometryMsgsPoseClass, obj.JavaMessage.getToPose);
            end
            topose = obj.Cache.ToPose;
        end
        
        function set.ToPose(obj, topose)
            %set.ToPose Set the value for property ToPose
            validateattributes(topose, {obj.GeometryMsgsPoseClass}, {'nonempty', 'scalar'}, 'robot_DeactivateCSSRequest', 'ToPose');
            
            obj.JavaMessage.setToPose(topose.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.ToPose)
                obj.Cache.ToPose.setJavaObject(topose.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.ToPose = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.ToPose = copy(obj.ToPose);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ToPose = feval([obj.GeometryMsgsPoseClass '.loadobj'], strObj.ToPose);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ToPose = saveobj(obj.ToPose);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.robot_comm.robot_DeactivateCSSRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.robot_comm.robot_DeactivateCSSRequest;
            obj.reload(strObj);
        end
    end
end
