classdef robot_SetTrackDistRequest < robotics.ros.Message
    %robot_SetTrackDistRequest MATLAB implementation of robot_comm/robot_SetTrackDistRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'robot_comm/robot_SetTrackDistRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '83ebed908297f9c3e07ef540f9857ab1' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        PosDist
        AngDist
    end
    
    properties (Constant, Hidden)
        PropertyList = {'AngDist', 'PosDist'} % List of non-constant message properties
        ROSPropertyList = {'ang_dist', 'pos_dist'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = robot_SetTrackDistRequest(msg)
            %robot_SetTrackDistRequest Construct the message object robot_SetTrackDistRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function posdist = get.PosDist(obj)
            %get.PosDist Get the value for property PosDist
            posdist = double(obj.JavaMessage.getPosDist);
        end
        
        function set.PosDist(obj, posdist)
            %set.PosDist Set the value for property PosDist
            validateattributes(posdist, {'numeric'}, {'nonempty', 'scalar'}, 'robot_SetTrackDistRequest', 'PosDist');
            
            obj.JavaMessage.setPosDist(posdist);
        end
        
        function angdist = get.AngDist(obj)
            %get.AngDist Get the value for property AngDist
            angdist = double(obj.JavaMessage.getAngDist);
        end
        
        function set.AngDist(obj, angdist)
            %set.AngDist Set the value for property AngDist
            validateattributes(angdist, {'numeric'}, {'nonempty', 'scalar'}, 'robot_SetTrackDistRequest', 'AngDist');
            
            obj.JavaMessage.setAngDist(angdist);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.PosDist = obj.PosDist;
            cpObj.AngDist = obj.AngDist;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.PosDist = strObj.PosDist;
            obj.AngDist = strObj.AngDist;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.PosDist = obj.PosDist;
            strObj.AngDist = obj.AngDist;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.robot_comm.robot_SetTrackDistRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.robot_comm.robot_SetTrackDistRequest;
            obj.reload(strObj);
        end
    end
end
